// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPxBMK8NGyq5f1I22vq1wBBq0UEy8DBd8',
    appId: '1:190437928717:web:ab81c4d29c32ad6919ca44',
    messagingSenderId: '190437928717',
    projectId: 'flutterapp-346ef',
    authDomain: 'flutterapp-346ef.firebaseapp.com',
    storageBucket: 'flutterapp-346ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3PpN1SGlTha5A15Bpj1VOynstJ_4T2o',
    appId: '1:190437928717:android:3ce2de1e9776a3f619ca44',
    messagingSenderId: '190437928717',
    projectId: 'flutterapp-346ef',
    storageBucket: 'flutterapp-346ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeZSNmjcSqUlYrUEQyzuOt0vw7Nrdd-1s',
    appId: '1:190437928717:ios:497f0c936711d80619ca44',
    messagingSenderId: '190437928717',
    projectId: 'flutterapp-346ef',
    storageBucket: 'flutterapp-346ef.firebasestorage.app',
    iosBundleId: 'com.example.mobileKakkakk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeZSNmjcSqUlYrUEQyzuOt0vw7Nrdd-1s',
    appId: '1:190437928717:ios:497f0c936711d80619ca44',
    messagingSenderId: '190437928717',
    projectId: 'flutterapp-346ef',
    storageBucket: 'flutterapp-346ef.firebasestorage.app',
    iosBundleId: 'com.example.mobileKakkakk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPxBMK8NGyq5f1I22vq1wBBq0UEy8DBd8',
    appId: '1:190437928717:web:b5dd8a59068105f719ca44',
    messagingSenderId: '190437928717',
    projectId: 'flutterapp-346ef',
    authDomain: 'flutterapp-346ef.firebaseapp.com',
    storageBucket: 'flutterapp-346ef.firebasestorage.app',
  );

}